#!/usr/bin/python3
#
# Kyle Hart
# 3 February 2018
#
# Project: sqlfat
# File: sqlfat
# Description: Executable interface for sqlfat parallel database.

import sys
import readline
from bin.client import Client
import re

usage = "sqlfat [host] [port]"
if len(sys.argv) < 2:
    print(usage)
    exit(1)

print("Welcome to SQLfat, a parallel database management system built around SQLite")

client = Client(sys.argv[1])
print("Connected to master node at " + client.host + ":" + str(client.port))

statement = ""

while "_quit" not in statement:
    statement = input("sqlfat > ")
    if "_quit" in statement:
        client.quit()
        print(client.response)
        print("Goodbye!")
        exit(0)
    else:
        client.execute(statement)
        if client.data is not None:
            for rows in client.data:
                print("\t\t".join(rows))
        print(client.response)



