#!/usr/bin/python3
#
# Kyle Hart
# 3 February 2018
#
# Project: sqlfat
# File: sqlfat
# Description: Executable interface for sqlfat parallel database.

import sys
import readline
from bin.client import Client

usage = "sqlfat [host] [port]"
if len(sys.argv) < 2:
    print(usage)
    exit(1)

print("Welcome to SQLfat, a parallel database management system built around SQLite")

client = Client(sys.argv[1])
print("Connected to master node at " + client.host + ":" + str(client.port))

statement = ""

while True:
    statement = input("sqlfat > ")
    # When quitting me must also tell the client to quit its connection with the master node
    if "_quit" in statement:
        client.quit()
        print(client.response)
        print("Goodbye!")
        exit(0)
    # Send statement to client, wait for status response. If response contains data then we print it.
    else:
        client.execute(statement)
        print()
        if client.data is not None:
            for rows in client.data:
                row_str = [str(x) for x in rows]
                flist = ['{:15}' for x in rows]
                print("".join(flist).format(*row_str))
        print(client.response)
        print()



