#!/usr/bin/python3
#
# Kyle Hart
# 3 February 2018
#
# Project: sqlfat
# File: sqlfat
# Description: Executable interface for sqlfat parallel database.

import sys
import readline
from bin.client import Client
import re

usage = "sqlfat [host] [port]"
if len(sys.argv) < 2:
    print(usage)
    exit(1)



print("Welcome to SQLfat, a parallel database management system built around SQLite")

client = Client(sys.argv[1])
print("Connected to master node at " + client.host + ":" + str(client.port))

statement = ""
while "_quit" not in statement:
    statement = input(">>>> ")
    if "_quit" in statement:
        print(client.quit())
        print("Goodbye!")
        exit(0)
    elif "_use" in statement:
        db = re.sub("_use ", "", statement)
        print(client.use(db))
    else :
        print(client.transaction(statement))

